import { Link } from "react-router-dom";
import { GridTexture, Reveal } from "../../components/retro";

const sections: Array<{ title: string; body: string[] }> = [
  {
    title: "1. Acceptance of terms",
    body: [
      "By creating an account, installing the CodeFerret GitHub App or Bitbucket integration, or otherwise using CodeFerret (\"the Service\"), you agree to these Terms. If you're using the Service on behalf of an organization, you're confirming you have authority to bind that organization.",
    ],
  },
  {
    title: "2. The service",
    body: [
      "CodeFerret reviews pull requests using large language models and posts findings as comments, a summary, and a status check. Findings are generated by AI and are provided as-is — CodeFerret does not guarantee that findings are complete, accurate, or that the absence of a finding means code is free of defects. You remain solely responsible for the code you ship.",
    ],
  },
  {
    title: "3. Accounts",
    body: [
      "You authenticate via GitHub or Bitbucket OAuth. You're responsible for maintaining the security of your connected accounts and for all activity that happens under your organization.",
    ],
  },
  {
    title: "4. Acceptable use",
    body: [
      "You agree not to: use the Service to review code you don't have the right to submit for review, attempt to circumvent plan/usage limits, reverse-engineer the Service, or use the Service in a way that violates GitHub's, Bitbucket's, Anthropic's, or OpenAI's own terms of service.",
    ],
  },
  {
    title: "5. Subscriptions & billing",
    body: [
      "Paid plans are billed on a recurring seat/usage basis via Razorpay. Fees are non-refundable except where required by law. You can cancel at any time from Settings; cancellation takes effect at the end of the current billing cycle. Failure to pay may result in your plan being downgraded to Free.",
    ],
  },
  {
    title: "6. Your code, your ownership",
    body: [
      "You retain all rights to your source code. CodeFerret is granted only a limited, revocable license to process your code (diffs and changed-file contents) for the sole purpose of generating a review, subject to the retention behavior described in the Privacy Policy. Self-hosted deployments never send code to CodeFerret's own infrastructure at all.",
    ],
  },
  {
    title: "7. Third-party services",
    body: [
      "The Service relies on GitHub, Bitbucket, Anthropic, OpenAI, Supabase, and Razorpay to operate. Your use of the Service is also subject to those providers' own terms. CodeFerret is not responsible for outages or changes on their end.",
    ],
  },
  {
    title: "8. Disclaimers & limitation of liability",
    body: [
      "The Service is provided \"as is\" without warranties of any kind. To the maximum extent permitted by law, CodeFerret is not liable for indirect, incidental, or consequential damages, including any damages resulting from a missed or incorrect finding, or from code shipped based on the Service's output.",
    ],
  },
  {
    title: "9. Termination",
    body: [
      "You may stop using the Service and uninstall the GitHub App / revoke the Bitbucket connection at any time. We may suspend or terminate access for violation of these Terms or non-payment.",
    ],
  },
  {
    title: "10. Changes to these terms",
    body: [
      "We may update these Terms from time to time. Continued use of the Service after a change takes effect constitutes acceptance of the updated Terms.",
    ],
  },
  {
    title: "11. Contact",
    body: ["Questions about these Terms: legal@codeferret.dev"],
  },
];

export default function Terms() {
  return (
    <div className="relative">
      <GridTexture />
      <div className="mx-auto max-w-3xl px-6 py-16">
        <Reveal>
          <p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#ffb300]">// legal</p>
          <h1
            className="mt-3 text-3xl font-bold uppercase tracking-tight text-[#f2ead9]"
            style={{ textShadow: "0 0 16px rgba(255,179,0,.2)" }}
          >
            Terms of Service
          </h1>
          <p className="mt-3 text-sm leading-relaxed text-[#a39a86]">Last updated: 2026-07-22</p>
        </Reveal>

        <Reveal className="mt-10 flex flex-col gap-6">
          {sections.map((s) => (
            <div key={s.title}>
              <h2 className="text-xs font-semibold uppercase tracking-wide text-[#f2ead9]">{s.title}</h2>
              {s.body.map((p, i) => (
                <p key={i} className="mt-2 text-sm leading-relaxed text-[#a39a86]">
                  {p}
                </p>
              ))}
            </div>
          ))}
        </Reveal>

        <p className="mt-10 text-xs text-[#6b6252]">
          See also the <Link to="/privacy" className="text-[#ffb300] hover:underline">Privacy Policy</Link>.
        </p>
      </div>
    </div>
  );
}
